### ISSUE TITLE
Challenge web view should removed from view on Success

### ISSUE THREAD

**Issue by milankamilya** [fjcaetano/ReCaptcha#111]
## Bug description
I have setup the invisible reCaptcha v2 and able to see the challenge page. On completing the challenge successfully, a white page remains in the screen. So, I can't go back to the main [application.](url)

## To Reproduce
1. Get a challenge page [refer first image]
2. Complete the challenge page successfully
3. Received token in closure
4. But, the white page is not removed from the view. [refer second image]

## Expected behavior
On successful completion of the challenge, the web view should have been removed from the screen.

## Logs
Nothing to mention

## Additional context
Nothing to mention

![Simulator Screen Shot - iPhone 12 Pro - 2021-09-15 at 18 44 23](https://user-images.githubusercontent.com/5398745/133442496-91f81c38-bdc5-4067-b98c-1089d30fdaf9.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-09-15 at 19 00 32](https://user-images.githubusercontent.com/5398745/133442523-71b3459b-12dd-4d09-91b6-87a50108a0cd.png)

**Comment by fjcaetano** [comment]
This seems to be a duplicate of #13 

@milankamilya can you take a look at [this comment](https://github.com/fjcaetano/ReCaptcha/issues/13#issuecomment-347030182) and see if that helps?

**Comment by milankamilya** [comment]
Thanks @fjcaetano for quick response.

Currently, I am removing the web view with a reference to it. But, I think it is library's responsibility to clean up the view after success.

**Comment by fjcaetano** [comment]
Glad to know it's all working for you. Why do you think the library should be responsible for removing the webview? Managing the UI is the developer's responsibility.

The only reason the library asks for a view is because WKWebView only starts executing JS content when its inserted into a view in the main window's hierarchy. If it weren't for that, the lib would only notify the developer that the challenge needs to be presented and leave that to them.

**Comment by milankamilya** [comment]
Thanks @fjcaetano.
