### ISSUE TITLE
Does nothing happend

### ISSUE THREAD

**Issue by nvduc2910** [fjcaetano/ReCaptcha#17]
I have just test with example but seems to not work. it's loading after press Validate button and I wait a long time but nothing happen. Please check

**Comment by fjcaetano** [comment]
It is working perfectly for me and for those who recently tested the library.

It's hard to look for anything without any information. Do you have any firewall limitations? Which device are you trying on? Whats the version you're using? Which iOS version are you running? Are you able to see any logs? Have you read and understood the docs?

**Comment by Majorzhang** [comment]
I have the same problem, it works fine for me last month, but recently it return nothing. 

I debug the code below , it seems right now this function does not work so that i can not receive token or error.
func handle(result: ReCaptchaDecoder.Result) {
        switch result {
        case .token(let token):
            completion?(.success(token))

        case .error(let error):
            completion?(.failure(error))

        case .showReCaptcha:
            configureWebView?(webView)

        case .didLoad:
            // For testing purposes
            webviewDelegate.execute()
        }
    }

Test Device: iPhone 6plus
ios Version: iOS 11

**Comment by fjcaetano** [comment]
@Majorzhang are you running on the alternate endpoint?

**Comment by Majorzhang** [comment]
@fjcaetano , both default  or alternate endpoint does not work ,  Google's API is not blocked.

**Comment by fjcaetano** [comment]
@Majorzhang and @nvduc2910 could you check if the branch `fix/alternate-endpoint` fixes it for you?

**Comment by MaximusMcCann** [comment]
Likewise, setup everything.  Call `validate`, but nothing happens.  I added `google.com/recaptcha` to the App Transport Security Settings as well, but still no luck.  

Side note, I set the key and domain in the `init` method, but use the default endpoint.

**Comment by fjcaetano** [comment]
It'd be great to know which iOS versions you are running. I was only able to reproduce it with the `.alternate` endpoint, so if you could provide me an example project where the issue is reproducible, I could dig further into it.

Still, there are changes to the `fix/alternate-endpoint` branch, it'd be great if you guys could checkout. I have added superficial tests to look for the issue I encountered with the alternate endpoint, but I don't know if it's the same thing you guys are running into.

Meanwhile, if it was the latest release that introduced this issue, keep pointing to the version `1.0.1` so the lib is still usable.

**Comment by MaximusMcCann** [comment]
@fjcaetano Repeatable every time.  

1. run `bundle install` // uses version `1.0.2`
2. set the apiKey and baseURL near the top of `ViewController`
3. Build & run
4. Click the button on screen.  (See code comments in `ViewController` and debug log)

[CaptchaTest.zip](https://github.com/fjcaetano/ReCaptcha/files/1644685/CaptchaTest.zip)

**Comment by MaximusMcCann** [comment]
Ran with an iPhone 8 Plus Simulator. iOS 11.2

**Comment by MaximusMcCann** [comment]
Xcode 9.2

**Comment by fjcaetano** [comment]
@MaximusMcCann are you adding `http` or `https` to the baseURL?

**Comment by fjcaetano** [comment]
@MaximusMcCann if your issue was indeed the domain, could you test the branch `fix/missing-url-scheme` and comment the results on issue #18, please?

**Comment by Majorzhang** [comment]
@fjcaetano  Finally i solved the problem by deleting the old ReCaptchaKey i created before (actually the old key worked in Dec but after a month ago it lost effect), after that i created a new key  to replace the old one and right now it worked.

**Comment by fjcaetano** [comment]
That's great @Majorzhang. I'm glad to know it's working for you
