### ISSUE TITLE
documentation: keys and use-cases

### ISSUE THREAD

**Issue by drzraf** [fjcaetano/ReCaptcha#2]
Hi,
I don't understand the use-case.
Let's say an application is using this library before submitting something to a remote server.
1. The "key" in this context would be the "public key" of the captcha. _You confirm?_
2. Then the g-response-message (that this library take care of) is going to be submitted to the server which will use it's secret key to verify the captcha. _Still right?_
3. In this context _what means ReCaptchaDomain?_
4. Sample show `recaptcha?.validate()`, _what means "validating" in this context?_
5. Sample use a `webview.frame` _is it still compatible with native app'_ not relying on webview?

thx!

**Comment by fjcaetano** [comment]
1. The `key` is the public key. Same as `data-sitekey` as described by the [ReCaptcha docs](https://developers.google.com/recaptcha/docs/invisible)
2. g-response-message will try to pre-check if the user is human or not, in which case it will return a valid secret or a challenge to be completed by the user which, in turn, returns the secret, if successful. The secret must then be sent to your backend for it to match against Google's API as described by the [server side validation](https://developers.google.com/recaptcha/docs/verify) of the process.
3. `ReCaptchaDomain` is the domain to which the key is associated to. When you [request for a key-pair](https://www.google.com/recaptcha/admin#list), you must provide a list of domains in which these keys are valid, to prevent cross-domain forgery. On the web you don't need to worry about providing this value because the website is already running on that domain, but on mobile, you must pass the domain to the API in order for the server to be able to validate the secret.
4. "Validating" means checking or not wether the user is human or not, this may return a valid secret, if successful, or it may return a challenge, that the user will have solve to prove he's not a robot.
5. If the API returns a challenge, the lib needs to show a webview with the challenge as on the example gif. In this case you will be provided the `UIWebView` to prepare it for presentation, which includes setting its frame. This is a native façade for the ReCaptcha lib, which is built for web, so the challenge it returns is an HTML that needs a webview to display.

**Comment by fjcaetano** [comment]
Let me know if you have any further questions, but I believe your confusion is more towards how the ReCaptcha validation process works rather than something related to this lib. I suggest you study the [ReCaptcha docs](https://developers.google.com/recaptcha/intro) in order to understand the process and its steps.

**Comment by drzraf** [comment]
I wanted to ensure to lib really act _as_ google's JS client-side
library.
Thank you very much for the answers. They clarify everything.

**Comment by fjcaetano** [comment]
Great. I hope you enjoy it. Also, feel free to open any PRs if you feel the need.
