### ISSUE TITLE
Support for Swift 4.1

### ISSUE THREAD

**Issue by CaliosD** [fjcaetano/ReCaptcha#49]
I've got an error of `/Carthage/Build/iOS/ReCaptcha.framework/ReCaptcha compiled with older version of Swift language (4.0) than previous files (unknown ABI version 0x06)` after intergrating this repo into my project with Carthage.

Would you please rebuild it and support this new version of Swift? Thanks in advance.

**Comment by fjcaetano** [comment]
@CaliosD have you tried telling Carthage to explicitly build the dependencies instead of relying on cached binaries?

`$ carthage update --no-use-binaries`

**Comment by CaliosD** [comment]
@fjcaetano Yep, I've cleared up the downloaded binaries and update it again. And it's the same.

**Comment by fjcaetano** [comment]
@CaliosD this is not an issue with the library. The binaries Carthage might be caching may have been compiled with a different Swift version than required by users. In these cases, you should tell Carthage to build the dependencies instead of relying on downloaded binaries.

We have just published a new release, however, I'd advise you to take a closer look at Carthage's output since it's supposed to build the lib for you.
