### ISSUE TITLE
Add to docs that you have to create an Invisible API key

### ISSUE THREAD

**Issue by hsavit1** [fjcaetano/ReCaptcha#5]
Let users know that they shouldn't make the mistake of creating a regular reCaptcha key

**Comment by fjcaetano** [comment]
Nice catch.

**Comment by netspencer** [comment]
Is there a technical limitation that requires this library to use the invisible key?

**Comment by fjcaetano** [comment]
@netspencer yes, this library is compatible only with the Invisible ReCaptcha, as stated in the docs

**Comment by netspencer** [comment]
> @netspencer yes, this library is compatible only with the Invisible ReCaptcha, as stated in the docs

Thanks for your reply. I guess I wasn't clear enough in my question. I'm in the process of evaluating the approach to take with ReCaptcha in my app. I would like to be able to use the same API Key that we are using on web, which is not an invisible key. 

Thus, I was looking for more technical insight into why this library only supports invisible keys. If I understood that more, I'd have a better overall understanding of my options.

I may go down the path of implementing this myself or forking this library to add support for the standard keys. But maybe that is a dead end. Just looking for some pointers before I waste my time. ;)

**Comment by fjcaetano** [comment]
I think I understood better what you need. The library does not work with non-invisible setup, but tbh, no one really tried looking into *why* it doesn't work, nor did anyone try making it work. I have a hunch that it's because you'd either have to show the ReCaptcha badge or a webview, during the whole process you may be trying to validate, but that's just a guess.

I think the first step here would by assessing exactly what is NOT working for that scenario. It might be the whole thing, which would be unfortunate, but it might also be just a case of intercepting the correct JS calls, as is done for the invisible key.

**Comment by netspencer** [comment]
> I think the first step here would by assessing exactly what is NOT working for that scenario. It might be the whole thing, which would be unfortunate, but it might also be just a case of intercepting the correct JS calls, as is done for the invisible key.

I'm going to take a look and let you know if I discover anything.

**Comment by netspencer** [comment]
I was able to get it working with regular ReCaptcha keys in a local fork. I will create a PR with some changes when I get the chance.
