### ISSUE TITLE
Captcha not appear at all

### ISSUE THREAD

**Issue by antons81** [fjcaetano/ReCaptcha#66]
## Bug description
I have implemented reCaptcha as shown on readme and it doesn't appear at all. in console logs, I see did load, executing resetting, but nothing appears. I have created recaptcha v2 Invisible type.

Update: While I am checking reset to false. It's started to enter inside Clojure, but falling with error unexpected

## Expected behavior
webview with captcha should be opened

## Logs
[JS LOG]: did load
[JS LOG]: executing
[JS LOG]: resetting

**Comment by fjcaetano** [comment]
@antons81 are you able to run the Example app? Also, have you tried the alternative endpoint?

**Comment by antons81** [comment]
@fjcaetano thanks for the response. Yes on example project working. I tried your key from sample project and it started to work on mine. But I want to use my own key. another issue. webview not disappeared, when I successfully passed captcha

**Comment by fjcaetano** [comment]
@antons81, it looks like you might have configured something wrong. Please, double check your keys and domain. Follow the same steps as if you're configuring a website.

If there's anything else I can help you with, let me know. I'm closing the issue for now since it doesn't seem to be related to the library.

**Comment by sergeydi** [comment]
@antons81 Hi, I have the same issue, do you found how to solve it?
