### ISSUE TITLE
No callback from ReCaptcha 

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [fjcaetano/ReCaptcha#72]
Hi, 
Currently we are using this library for Google ReCaptcha in apps, for now in development state. 
While this library was integrated for long time and just now ( like week ago ) we started to have issues with this library. 
I thought that this was fault of our code / configuration, but after debugging i found that in some cases user is stuck on sign in / sign up because of no response from ReCaptcha library. 

our "sign up"  flow: 
- type credentials 
- get recaptcha token 
- send recaptcha token along with credentials to API 

## To Reproduce
- try to use wrong password to be able to invoke captcha multiple times 
- repeat until you get following log from webview: 

#CAPTCHA LOG: 
"[\"log\": did load]"
 "[\"log\": executing]"
 "[\"log\": resetting]"
- then completion block will not be called 

## Bug description
Since there is no completion block, app will wait for ReCaptcha result infinitely

## Expected behavior
Library always respond with callback ( either error / token / challange ) 

## Logs
responses from webview ( ReCaptchaDecoder::handle )
```
 "[\"log\": did load]"
 "[\"log\": executing]"
 "[\"log\": resetting]"
```
## Additional context
I noticed that this issue more often occurs on real devices rather than on simulators 
device i used for debugging: iPhone 7 with iOS 12.1.4

I also tried to find documentation for ReCaptcha and the things you've implemented, but i couldn't find them. Could you share some links in response? 
(this [official link](https://developers.google.com/recaptcha/docs/invisible) is not sufficient for me, there is no information about statuses)

**Comment by NosovPavel** [comment]
I have the same behaviour and similar flow. My app is using 1.4.0 version and it's working but not all the time. I tried to update to latest 1.4.2 but it didn't solve the problem.

**Comment by fjcaetano** [comment]
@Przemyslaw-Wosko and @NosovPavel, please, set `resetOnError: false` and paste the error you're receiving here.

**Comment by smokyfire** [comment]
Same for me, exactly what @NosovPavel said. Sometimes I get no callback from the validate() method.

**Comment by fjcaetano** [comment]
A few things to bare in mind:
1. `reset()` must be called in between validates. If you try to validate twice in a row, it won't work
2. `resetting` is being logged because `validate(on:)` is being called with `resetOnError: true`, which is the default if you don't pass it.
3. Since reset is being called, it doesn't throw the error it's receiving.
What do you need to know in regards of the documentation? All JS methods being used are there. 

Regarding statuses, we can only know if there's a token. Any errors thrown by JS are captured and rethrown to the result callback. Google's library doesn't provide any way of figuring out if the challenge needs to be displayed, we try to identify that by monitoring the DOM [which can be seen here](https://github.com/fjcaetano/ReCaptcha/blob/master/ReCaptcha/Assets/recaptcha.html#L38). Since this is something implemented in this repository, it may be prone to errors due to updates in the JS library.

Please, try to provide some errors or a working example (in a separate repo), or maybe change the ReCaptchaKey and Domain in the Example project to the ones you're using so we can try to investigate further. There's not much to go on in this issue with the current information we have.

**Comment by NosovPavel** [comment]
@fjcaetano thanks for your reply, I made few changes in my project with `reset()` but it didn't help. So there is [short video](https://drive.google.com/file/d/19iiAuJL5ZHVptkviWSFUGqnaQDgiY0Gs/view?usp=sharing) with an example of this repository that didn't work as I expected and the [source code ](https://drive.google.com/file/d/1uifxOQ7QYT0VUyb0X0lfWjk6AsPWDQRL/view?usp=sharing) (it's the same as yours). Could you say what's wrong and what should I do to fix this?

**Comment by fjcaetano** [comment]
Thanks @NosovPavel, I was able to reproduce the issue in the project you gave and I'm investigating it. Also your video was really helpful! Good stuff

**Comment by Przemyslaw-Wosko** [comment]
@fjcaetano any news? can we help you somehow with that?

**Comment by fjcaetano** [comment]
@Przemyslaw-Wosko I'm sorry for halting this. I'm currently with little time to focus on any open source project. Any help with this project is appreciated.

I was able to narrow the issue down to the logic that checks if all resources have already been loaded before triggering the JS validation. I have some WIP code in the branch `fix/resource-validation` that should already be improving the situation a bit.

I'd love to hear your feedback on it since it has mitigated the issue a lot on my end. It still needs a bit of work before being ready to merge onto `master` so, if you want to, feel free to improve it.

**Comment by fjcaetano** [comment]
Folks, I just deployed version 1.5.0 with the new resource validation logic. I also added a new feature: there's now a callback on didFinishLoading so you can list to it.

I know this is boring and cumbersome, but I'd really like to hear your feedback on it. This should ease development if you're having any issues related to the loading of resources.

**Comment by cyber-gh** [comment]
Same issue here, but I am unable to update to version 1.5.0 from cocoapods. Is the new version live yet ?

**Comment by fjcaetano** [comment]
@cyber-gh sorry, there was an issue with the deploy to CocoaPods, please try again, everything should be fine now.

**Comment by cyber-gh** [comment]
> @cyber-gh sorry, there was an issue with the deploy to CocoaPods, please try again, everything should be fine now.

Seems to be working now. Thanks.

**Comment by fjcaetano** [comment]
Does this means the issue has been fixed?

**Comment by cyber-gh** [comment]
Yes, the issue has been fixed. Sorry for late response.
