### ISSUE TITLE
reset func appear endless resetting.

### ISSUE THREAD

**Issue by yildirimatcioglu** [fjcaetano/ReCaptcha#90]
When I call reset func after a successfull validation, it gives an endless resetting output.
Here is the output on console:
[JS LOG]: executing
[JS LOG]: resetting

I try to open for a new validation. Before the second validation call I call reset func and here is the output.
Also, example project don't work second time.

**Comment by fjcaetano** [comment]
Hi @yildirimatcioglu. There's very little information to be able to assess anything here. If the Example project is working, that's a sign that the library is behaving properly and should be working for you too, unless you have misconfigured something.

You should **always** call `reset()` between each `validate()` call. Google's JS library does not allow validating more than once without resetting. The Example project does not do that out of the box, which can be seen in the code.

If you're able to provide a sample code we can try and dig further into this, but there's almost nothing that can be done with the information at hand.

**Comment by vaverkax** [comment]
I've also run into this problem and solved it in my way( I think not the right one)

every time when user entered wrong code I need to reload recaptcha
So I did it like this:
1) recaptcha view is created not like global variable but it local stack( eg when user tap button)
2) proceed to validate recaptha
3) if user entered wrong code (recatpcha validate successfully ) I search WKWebView on screen and remove it from superview

and you can repeat it

I think this solution can be improved but for now I don’t have much time to do this 😕

**Comment by fjcaetano** [comment]
@vaverkax what do you mean by "user entered wrong code"? The user shouldn't input any codes, they should only solve the challenge if the captcha asks for it, but the result received in the completion closure shouldn't be a `.token()` unless the captcha has successfully validated the user.

Anyway, your approach is being "better safe than sorry" by removing the webview every time, but it works. Removing the webview is the developers' responsibility, since the library does not handle that. In all fairness, the library only asks for a view because WebKit does not start the JSVM if the webview is not in the view hierarchy. IMHO that's super weird, because we should be able to run JS code without it being bound to any UI, but that's how the SDK works.

A couple of ways you can improve your implementation is by:
1. Saving a reference to the current webview. Then you should always remove the previous reference when you receive a new event on `configureWebView`.
2. Setting a custom tag to the webview. Pretty similar to 1, but you don't need to save any references. (This is how the example works)

**Comment by vaverkax** [comment]
@fjcaetano it’s just a business logic
User must enter code from sms just like he entered a password
And then he must challenge the captcha (it’s not my decision to do like that))

As for your advices:
Setting tag for view it good idea, thanks. I’ll do that.
As for saving the reference - I think it was clearly understood so I dint mention it in my solution 😁

**Comment by fjcaetano** [comment]
Any updates on this issue? May I close it?
