### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by JAiden78** [fjcaetano/ReCaptcha#99]
I was trying to use this , but at the point where we call configure webview from viewdidload() , it doesn't return any value , completion handler never get called. I put my keys in info plist file and when i create recaptcha object with try it gets initialized but after that nothing happens in viewdidload , Kindly guide me how to resolve this issue.

**Comment by fjcaetano** [comment]
Hey @JAiden78, it's hard to help you without any info. Please, try to follow the issue template since it's designed to help you troubleshoot your problem and to give the most relevant information so we can try and investigate what's happening.

I'll close this issue since it's in the wrong format, so please, open a new one following the template
